"""empty message

Revision ID: 2223470f43e9
Revises: a911dde905c7
Create Date: 2024-08-31 11:48:24.273810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2223470f43e9'
down_revision: Union[str, None] = 'a911dde905c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faces', schema='face_verification_schema')
    op.create_table('faces',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('vector', sa.Text(), nullable=False),
                    sa.Column('path_to_image', sa.String(length=1024), nullable=False),
                    sa.Column('creation_time', sa.DateTime(timezone=True),
                              server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='face_verification_schema'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faces', schema='face_verification_schema')
    # ### end Alembic commands ###
