"""empty message

Revision ID: a911dde905c7
Revises: 2a0d963e527e
Create Date: 2024-08-21 10:32:15.523071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a911dde905c7'
down_revision: Union[str, None] = '2a0d963e527e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.String(length=1024), nullable=False),
    sa.Column('path_to_image', sa.String(length=1024), nullable=False),
    sa.Column('creation_time', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='face_verification_schema'
    )
    op.drop_table('faces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('path_to_image', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], name='faces_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='faces_pkey')
    )
    op.drop_table('faces', schema='face_verification_schema')
    # ### end Alembic commands ###
